/*
 * This Java source file was generated by the Gradle 'init' task.
 * THis class tests the functions in APP.java
 */
package edu.duke.ks713.battleship;

import org.junit.jupiter.api.Test;
import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    /**The test function simulates the situiation that player A won the game
     * @throws IOException for calling methods*/
@Test
public void version1_finalTest_A_won() throws IOException{
    ArrayList<String> inputList=new ArrayList<String>();
    inputList.add("A0V");
    inputList.add("C0V");
    inputList.add("E0V");
    inputList.add("H0V");
    inputList.add("K0V");
    inputList.add("N0V");
    inputList.add("A1H");
    inputList.add("B1V");
    inputList.add("H1V");
    inputList.add("B3V");
    ArrayList<String> corString=new ArrayList<String>();
    for(char i='A';i<='T';i++){
        for(int j=0;j<=9;j++){
            corString.add(Character.toString(i)+j);
        }
    }
    ArrayList<String> allInputs=new ArrayList<>();
    for(String s1:inputList){
        allInputs.add(s1);
        if(s1.equals("B3V")==false){
            allInputs.add("CC");
        }
    }
    for(String s2:inputList){
        allInputs.add(s2);
    }
    for(String s3:corString){
        allInputs.add(s3);
        allInputs.add(s3);
    }
    String sumI="";
    for(String s5: allInputs){
        sumI+=s5+"\n";
    }
    InputStream in1=new ByteArrayInputStream(sumI.getBytes());
    System.setIn(in1);
    App.main(new String[0]);
}
/**The test function simulates the situation that B won the game
 *  @throws IOException for calling methods**/
@Test
public void version1_finalTest_BWon() throws IOException{
    ArrayList<String> inputList=new ArrayList<String>();
    inputList.add("A0V");
    inputList.add("C0V");
    inputList.add("E0V");
    inputList.add("H0V");
    inputList.add("K0V");
    inputList.add("N0V");
    inputList.add("A1H");
    inputList.add("B1V");
    inputList.add("H1V");
    inputList.add("B3V");
    ArrayList<String> corString=new ArrayList<String>();
    for(char i='A';i<='T';i++){
        for(int j=0;j<=9;j++){
            corString.add(Character.toString(i)+j);
        }
    }
    ArrayList<String> allInputs=new ArrayList<>();
    for(String s1:inputList){
        allInputs.add(s1);
        if(s1.equals("B3V")==false){
            allInputs.add(s1);
        }
    }
    for(String s2:inputList){
        allInputs.add(s2);
    }
    for(String s3:corString){
        allInputs.add("B8");
        allInputs.add(s3);
    }
    String sumI="";
    for(String s5: allInputs){
        sumI+=s5+"\n";
    }
    InputStream in1=new ByteArrayInputStream(sumI.getBytes());
    System.setIn(in1);
    App.main(new String[0]);
}
/**The test function of EOF exception
 *  @throws IOException for calling methods**/
@Test
public void version1_finalTest_readCoordinateEOFexception() throws IOException{
    ArrayList<String> inputList=new ArrayList<String>();
    inputList.add("A0V");
    inputList.add("C0V");
    inputList.add("E0V");
    inputList.add("H0V");
    inputList.add("K0V");
    inputList.add("N0V");
    inputList.add("A1H");
    inputList.add("B1V");
    inputList.add("H1V");
    inputList.add("B3V");
    ArrayList<String> corString=new ArrayList<String>();
    for(char i='A';i<='T';i++){
        for(int j=0;j<=9;j++){
            corString.add(Character.toString(i)+j);
        }
    }
    ArrayList<String> allInputs=new ArrayList<>();
    for(String s1:inputList){
        allInputs.add(s1);
    }
    for(String s2:inputList){
        allInputs.add(s2);
    }
    for(String s3:corString){
        allInputs.add("SS");
        allInputs.add(s3);
    }
    String sumI="";
    for(String s5: allInputs){
        sumI+=s5+"\n";
    }
    InputStream in1=new ByteArrayInputStream(sumI.getBytes());
    System.setIn(in1);
   //App.main(new String[0]);
   assertThrows(EOFException.class,()->App.main(new String[0]));
}
/**The test function for EOF exception
 *  @throws IOException for calling methods**/
@Test
public void version1_finalTest_readPlacementEOFexception() throws IOException{
    ArrayList<String> inputList=new ArrayList<String>();
    inputList.add("A0V");
    inputList.add("C0V");
    inputList.add("E0V");
    inputList.add("H0V");
    inputList.add("K0V");
    inputList.add("N0V");
    inputList.add("A1H");
    inputList.add("B1V");
    inputList.add("H1V");
    inputList.add("B3V");
    ArrayList<String> corString=new ArrayList<String>();
    for(char i='A';i<='T';i++){
        for(int j=0;j<=9;j++){
            corString.add(Character.toString(i)+j);
        }
    }
    ArrayList<String> allInputs=new ArrayList<>();
    for(String s1:inputList){
        allInputs.add(s1);
    }
    String sumI="";
    for(String s5: allInputs){
        sumI+=s5+"\n";
    }
    InputStream in1=new ByteArrayInputStream(sumI.getBytes());
    System.setIn(in1);
   // App.main(new String[0]);
    assertThrows(EOFException.class,()->App.main(new String[0]));
}
}
