/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ks713.battleship;

import org.junit.jupiter.api.Test;
import java.io.*;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
@Test
public void version1_finalTest() throws IOException{
App.main(new String[2]);
}
}
